public with sharing class firstclass {
    public firstclass() {
        String a = '123';
        String b = '123';
        String c = '123';
        // git cmd test
        // git cmd test2
        // git cmd test3
        // git cmd test4
        // final git cmd test5
        // multi test git cmd test1
        // multi test git cmd test2
        // multi test git cmd test3
        // multi test git cmd Auto Trigger
        // multi user save email
        // vs TEST 2
        // vs TEST 3
        // vs Test 4
    }
}